#!/usr/bin/env bash
# checking if all 4 required parameters are provided
if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Store the parameters in variables

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4


# Disable strict host key checking for added convenience
scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

# Check the exit status of scp to determine if the transfer was successful
if [ $? -eq 0 ]
then
  echo "FILE TRANSFER WAS SUCCESSFULL"
else
  echo "FILE TRANSFER FAILED"
fi
