#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 100

x=1
while [ $x -ne 101 ]
do
    if [ $((x % 15)) -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $((x % 3)) -eq 0 ]
    then
	echo "Fizz"
    elif [ $((x % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
	echo $x
    fi
    ((x++))
done
