#!/usr/bin/env bash
# prints bad luck for the fourth loop iteration,
good luck on the 8th loop iteration, and Best
School on other iterations

x=1

while ((x <= 10))
do

	if ((x == 4))
	then
		echo "bad luck"
	elif ((x == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	x=$((x+1))
done
