#!/usr/bin/env bash
#Displays the time for for 12 hours
#and 59 minutes

x=0
y=1

while [ $x -le 12 ]; do
	echo "Hour: $x"
	while [ $y -le 59 ]; do	
		echo "$y"
		y=$((y+1))
	done
	y=$((1))
	x=$((x+1))	
done
