#!/usr/bin/env bash
# Script that displays content of the current directory
#	In a list format, where only the part of
#	the name after the first dash is displayed

for x in *; do
    echo "$x" | cut -d '-' -f 2

done
